### ISSUE TITLE
Bookmarks not highlighted after atom restart

### ISSUE THREAD

**Issue by pcan** [atom-minimap/minimap-bookmarks#1]
When I place some bookmarks around, the minimap display them correctly, but if atom is restarted, only the line number bar shows the bookmark icon, and the blue line in the minimap is not visible any more. The only way to show it is to remove and add the bookmarks again.

**Comment by abe33** [comment]
Hi and thanks for the report, it doesn't look like a hard thing to fix, I'll try to find some time in the next week to fix that.

**Comment by pcan** [comment]
Ok, thanks! :+1:

**Comment by J5lx** [comment]
Any news on that?

**Comment by abe33** [comment]
Sorry everyone, got carried away by my other projects, I'll try to take some time today to look at that seriously.

**Comment by abe33** [comment]
I finally took the time to fix this :)

**Comment by J5lx** [comment]
Awesome, thanks!
