### ISSUE TITLE
[q] bookmarks in minimap are not shown when using persistent-bookmarks pkg

### ISSUE THREAD

**Issue by Sfinx** [atom-minimap/minimap-bookmarks#122]
I'm using the https://atom.io/packages/persistent-bookmarks as want my bookmarks survive over atom closing. But minimap-bookmarks do not display them despite Atom shows the bookmark in editor ok. What can be the problem ?

TIA

**Comment by UziTech** [comment]
It doesn't look like persistent-bookmarks saves the bookmarks the same way as bookmarks so minimap-bookmarks can't pick them up. If you want to work on adding a way for minimap-bookmarks to work with persistent-bookmarks I would be happy to add it.

**Comment by Sfinx** [comment]
Can't find example how the bookmarks are saved. All I've found is entry in IndexedDB:

```
bookmarks:
2:
markerLayerId: "54"
17:
markerLayerId: "152"
24:
markerLayerId: "35"
39:
markerLayerId: "24"
```

Closing this as found a way to save the bookmarks using stock package. Thanks for reply !
