### ISSUE TITLE
Usage Documentation

### ISSUE THREAD

**Issue by shylor** [atom-minimap/minimap-bookmarks#4]
I love what this is trying to do, but I have no clue how to use it. Can you please update the readme with key bindings or how to use this or a link to where to look to use this?

**Comment by faellacurcio** [comment]
https://github.com/atom/bookmarks

**Comment by abe33** [comment]
Sorry, I missed the notification for this issue, it's just as @faellacurcio mentionned, this is mostly a binding to display bookmarks from the core package into the minimap, however, the new version on beta and master is now using decorations layer and so the bookmarks can no longer be retrieved with the current implementation so it'll need to be fixed.

**Comment by stewhouston** [comment]
+1

Loved this package but it has stopped working for me entirely.

**Comment by fundon** [comment]
Update to v0.4.0, It's re-working.
