### ISSUE TITLE
Bookmarks don't appear on minimap

### ISSUE THREAD

**Issue by Dbuggerx** [atom-minimap/minimap-bookmarks#5]
Since Atom 1.8, I'm unable to see the bookmarks on the minimap. 
I'm now running Atom 1.9.6 (Fedora Linux), and the issue persists.
Does it happen to anyone else?

**Comment by DarekDeo** [comment]
Same here, Atom 1.9.4 on Linux.

**Comment by Fixluja** [comment]
Same issue in Atom 1.9.7 on Mac OS X 10.11.6

**Comment by jeroldalbertson-wf** [comment]
Diddo. Atom 1.9.4 on Mac OS X 10.11.6

**Comment by kaiKitsune** [comment]
Same. Aton 1.9.8 on win7x64

**Comment by leedorian** [comment]
Same here, Atom 1.9.9 win10 x64

**Comment by fundon** [comment]
Thank you for your reports.

I'm working on it.

**Comment by fundon** [comment]
Upgrade to V0.4.0.

**Comment by JeOam** [comment]
Same issue in Atom 1.9.9 on Mac OS X 10.11.6 with V0.4.1

**Comment by fundon** [comment]
@JeOam Need more details. Thanks.

It's ok on macOS 10.12 Beta 6.

**Comment by JeOam** [comment]
@fundon Thanks for your reply.

I am not sure what `more details` means, here is the community packages I used in Atom:
```
├── Sublime-Style-Column-Selection@1.7.2
├── atom-html-preview@0.1.22
├── atom-typescript@10.1.6
├── atom-vue@0.11.0
├── autosave@0.23.1
├── close-unmodified-tabs@1.0.1
├── language-vue@0.15.1
├── language-vue-component@0.4.7
├── linter@1.11.16
├── linter-eslint@7.2.4
├── minimap@4.24.7
├── minimap-autohide@0.10.1
├── minimap-bookmarks@0.4.1
├── node-debugger@1.7.0
├── open-in-browser@0.4.7
├── open-recent@5.0.0
├── react@0.16.0
└── vue-autocomplete@0.1.0
```

**Comment by abe33** [comment]
It's clearly not working in the most simple use, which is to open a file and adding a bookmark. So I'll reopen.

**Comment by maorefaeli** [comment]
Hey,
I have the same problem with Atom 1.8 and V0.4.2
